dataset: cifar10
aa: null
batch_size: 96
color_jitter: 0.0
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
drop_path_rate: 0.2
drop_path_strategy: linear
epochs: 600
log_interval: 50
lr: 0.175
min_lr: 1.0e-05
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 1.0
auxiliary: True
auxiliary_weight: 0.4
sched: cosine
seed: 42
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 3.0e-05
workers: 4
