aa: null
batch_size: 128
color_jitter: 0.4
decay_by_epoch: True
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
epochs: 250
log_interval: 50
lr: 0.5
min_lr: 1.0e-05
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: linear
auxiliary: True
auxiliary_weight: 0.4
seed: 42
warmup_epochs: 5
warmup_lr: 0.0125
weight_decay: 3.0e-05
workers: 4
