backbone:
    # name: [n, stride, in_channels, out_channels, expand_ratio, op]
    conv_stem: [1, 1, 3, 32, 1, 'conv3x3']
    stage_0: [2, 2, 32, 64, 6, 'ir_3x3']
    stage1: [3, 2, 64, 128, 6, 'ir_3x3']
    stage2: [3, 2, 128, 256, 6, 'ir_3x3']
    conv_out: [1, 1, 256, 1280, 1, 'conv1x1']
    gavg_pool: [1, 1280, 1280, 1, 'gavgp']
head:
    linear1:
        dim_in: 1280
        dim_out: 10

