dataset: imagenet
aa: null
batch_size: 32
color_jitter: 0.0
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
epochs: 120
log_interval: 50
lr: 0.1
smoothing: 0.0
min_lr: 1.0e-07
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: cosine
seed: 42
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 1.0e-04
workers: 4
# dyrep
dyrep: False
dyrep_adjust_interval: 5
dyrep_recal_bn_every_epoch: False
dyrep_max_adjust_epochs: 100
