aa: rand-m9-mstd0.5
batch_size: 128
color_jitter: 0.0
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
# dropout
drop: 0.0
drop_path_rate: 0.1

epochs: 300
log_interval: 50
lr: 1.e-3
min_lr: 1.0e-05
model_ema: False
model_ema_decay: 0.99996
momentum: 0.9
opt: adamw
opt_betas: null
opt_eps: 1.0e-08

interpolation: 'bicubic'

# random erase
remode: pixel
reprob: 0.25

# mixup
mixup: 0.8
cutmix: 1.0
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'

sched: cosine
seed: 42
warmup_epochs: 5
warmup_lr: 1.e-6
weight_decay: 0.05
workers: 8
