dataset: cifar10
aa: null
batch_size: 256
color_jitter: 0.0
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
epochs: 50
log_interval: 50
lr: 0.1
smoothing: 0.0
min_lr: 1.0e-05
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: cosine
seed: 42
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 5.0e-04
workers: 4
