aa: rand-m9-mstd0.5
batch_size: 192
decay_by_epoch: false
decay_epochs: 2.4
decay_rate: 0.97
drop: 0.2
epochs: 240
log_interval: 50
lr: 0.6
min_lr: 1.0e-06
model_ema: true
model_ema_decay: 0.9999
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 0.001
remode: pixel
reprob: 0.4
sched: cosine
seed: 42
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 1.0e-04
workers: 4
